### ISSUE TITLE
Deal with data issues

### ISSUE THREAD

**Issue by meitianyyp** [ShangwenWang/Cognac#3]
Hi, I'm having trouble getting the token sequence in the first step. After parsing the code through Javalang,I can't get the token sequence, and the type of each token. There is an error that the parsed AST does not have a token sequence. Can you help me?

method.tokens = AST.tokens
The AST does not have a token attribute.

**Comment by ShangwenWang** [comment]
Hi, have you installed the javalang package modified by ourselves? The link was given in the README file.

**Comment by meitianyyp** [comment]
Thank you, I have used the modified Javalang package
