### ISSUE TITLE
Code implementation error

### ISSUE THREAD

**Issue by ddf1826120803** [ShangwenWang/Cognac#5]
In the file decode.py: 
1) line 116, you ignore the return value 'enc_stmts'(expected 7, actually 8)
2) line 119 and line 164, call the "self.model.encoder/self.model.decoder", you miss one parameter.

**Comment by ShangwenWang** [comment]
Hi thanks for pointing out this. Actually we use **decode_type.py** in the experiment.

We will fix it in the Shell script.
