### ISSUE TITLE
Quesstions about MCC task?

### ISSUE THREAD

**Issue by binglinchengxiash** [ShangwenWang/Cognac#6]
Thanks your great work!
In step4,  I have a problem.
![image](https://user-images.githubusercontent.com/15050040/158775332-e0ae7f94-49a2-46aa-ac1f-3fa25d50ccd0.png)

**Comment by ShangwenWang** [comment]
Hi did you modify something? I did not meet such a problem

**Comment by binglinchengxiash** [comment]
> Hi did you modify something? I did not meet such a problem

I did not modify anything.

**Comment by binglinchengxiash** [comment]
> Thanks your great work! In step4, I have a problem. ![image](https://user-images.githubusercontent.com/15050040/158775332-e0ae7f94-49a2-46aa-ac1f-3fa25d50ccd0.png)

In the file decode_mcc.py:
line 80, the len_recall variable is 10. 
![image](https://user-images.githubusercontent.com/15050040/158923286-553733fe-dcb2-4047-92cd-d679de75947b.png)

**Comment by ShangwenWang** [comment]
https://github.com/ShangwenWang/Cognac/issues/4#issuecomment-955204756

I guess you are trying on your own data. In our experiment, we limit the number of tokens for a single method name (cf. the above link to another issue). Therefore, we do not meet such a problem.

**Comment by binglinchengxiash** [comment]
I did not use my own dataset.I used the data set you provided: Java Large.

**Comment by ShangwenWang** [comment]
Ok. Then just make a pre-processing. Filter those bloated method names and the code can work.

**Comment by binglinchengxiash** [comment]
> Ok. Then just make a pre-processing. Filter those bloated method names and the code can work.

ok，thanks
