### ISSUE TITLE
Regarding the data generation

### ISSUE THREAD

**Issue by FalconLK** [ShangwenWang/Cognac#7]
Hello, thank you very much for sharing your great work ! 

I am so sorry to disturb you! I'm facing some problems when running the dataset generation. 
I hope you can help me to solve it! Thank you in advance :) 

If I'm not wrong, 
====Step 1====
**dataextractor.py** 
input: 
java-small/training
java-small/validation
java-small/test
![Screenshot 2022-08-25 at 3 40 19 PM](https://user-images.githubusercontent.com/34045340/186605657-9a829aa9-b146-432d-bd5d-e5e2f2a5b346.png)

output:
training.json
validation.json
test.json
<img width="716" alt="Screenshot 2022-08-25 at 3 40 45 PM" src="https://user-images.githubusercontent.com/34045340/186605813-97353658-136b-4351-8f12-836f433733da.png">

====Step 2====
**train_fasttext.py**
input:
training.json
validation.json
test.json
![Screenshot 2022-08-25 at 3 40 27 PM](https://user-images.githubusercontent.com/34045340/186605768-0e636c2a-563b-45e1-bc5b-ff3999cec577.png)

output:
fasttext_vectors/vocab.pkl
fasttext_vectors/weight.pkl

**vocab.pkl is only 58 bytes and weight.pkl is 2206 bytes**
<img width="420" alt="Screenshot 2022-08-25 at 3 45 16 PM" src="https://user-images.githubusercontent.com/34045340/186606012-b62c7ceb-1d6b-4b89-8825-b162b1095390.png">

I checked inside the code (**train_fasttext.py**) and figured that the json2corpus method has split(', '). However, I don't have the same expression in the JSON files generated by Step 1 (**dataextractor.py**).
![Screenshot 2022-08-25 at 3 41 10 PM](https://user-images.githubusercontent.com/34045340/186606696-dbdb96ac-5a3c-4b1c-a37f-6729c81ba0cf.png)

Could you please kindly advise me on how I can fix this problem?

**Comment by ShangwenWang** [comment]
Don't know why it happens.

Maybe you can try to modify the saveResults faunction in dataextractor.py. Just save the token sequence and method name in two json lists separated by ", ".

**Comment by FalconLK** [comment]
@ShangwenWang , Thank you very much for your reply bro! I truly appreciate it. 

You're saying that the right format would be like the following? 

{['["domain",14],["peer",14],["server",14],["domain",19],["socket",19],["domain",34],["socket",34],["string",36],["return",29],["new",29],["domain",29],["socket",29],["path",29],["fd",29],["validate",20],["socket",20],["path",20],["security",20],["path",20],["int",21],["fd",21],["string",34],["string",36],["int",36],["return",29],["path",29],["replace",29],["string",29],["value",29],["of",29],["port",29],["this",1],["sock",1],["sock",1]**', '**["domain","peer","server"]']}

If it's not the correct format, the simplest way for us would be to look at an example. 
Could you please provide a simple example, so that I can modify the code following the example ;)

**Comment by ShangwenWang** [comment]
I guess this format could work. You can have a try.

I'm sorry I cannot give you any example now. I am in Shenzhen now but the server I used is still in Changsha.

**Comment by FalconLK** [comment]
No problem bro :) I can try first! 

I already really appreciate that you're still answering haha 

I'll let you know how it goes !

**Comment by FalconLK** [comment]
First of all, dataextractor.py generates the lists of [tokens-number], as we can see in the lines (464), and append the oracle in the last step. 
![Screenshot 2022-08-26 at 4 58 55 AM](https://user-images.githubusercontent.com/34045340/186769478-25a55363-75e9-4b2f-bc96-c235dd57df7c.png)

For example, 
![Screenshot 2022-08-26 at 4 57 53 AM](https://user-images.githubusercontent.com/34045340/186769518-dee65536-0488-4cad-9778-5fa537bd7e45.png)

Second, the train_fasttext.py process the result file above.

![Screenshot 2022-08-26 at 4 55 50 AM](https://user-images.githubusercontent.com/34045340/186769619-6fc04944-0c99-4f6e-9d3a-6db92252c7af.png)

The code here splits the method_json (each line of the file) with ‘, ‘ (comma + white space). As we discussed in the previous comments, there is no comma + white space pattern. 

Once I manually add a white space right before the oracle, the variable “fst_part” will be having like  “[["file",14],["void",15],["throw",7],["new",7],["runtime",7],["exception",7],["on",7]”

and 

“sec_part” will have like 
“["delete","on","exit"]]”

Each of them is not loadable by json.load(). 

I have tried the dictionary format as well. Like the below. 
![Screenshot 2022-08-26 at 5 05 37 AM](https://user-images.githubusercontent.com/34045340/186769710-cb5eb504-a3c2-47b7-b591-d5548b4e75f5.png)

However, we also have “cur_line = token + test_name” at line number 37 in train_fasttext.py, which is not possible since it’ll be dict + list.

I would like to ask you when you’re going back or if you can access the server with VPN or something :)

**Comment by ShangwenWang** [comment]
I really don't know the exact date. 

Maybe you could modify the correponding code. Store the info into two lists and then they can be combined.

**Comment by FalconLK** [comment]
Thank you for your reply Shangwen :) 

I assume that you mean by two lists like following:
[["android",14],["application",14],["view",15]], ["initialize","for","view"]]
[first_part, second_part]

However, if I'm not wrong, we need to input sentences into word2vec later. In the above case, we're delivering 
each of ["android", 14], ["application", 14], ["view", 15] into word2vec. Feels like something process is missing. 

I tried and got the following error message. 
<img width="716" alt="Screenshot 2022-08-26 at 7 11 11 PM" src="https://user-images.githubusercontent.com/34045340/186891937-13beb408-8519-475a-b396-d2a9c9d1c9da.png">

Should we modify the code and parse the json to get each word and put them into word2vec ? 

I'm so sorry to disturb you. I didn't mean to ask you this much.. T-T but I would love to successfully replicate your great work.

**Comment by GuodongFan** [comment]
I think you can try with those commented-out codes. @FalconLK 

```
           method_json = json.loads(method_json)

            content = method_json[0]

            name = method_json[1]

            cur_line = method_json[-1]

            #cur_line = method_json[-1] + method_json[-2]  # only for kuis dataset

            for x in method_json[:-1]:

            # for x in method_json[:-2]:  # only for kuis dataset

                 if is_alpha(x[0]):

                     cur_line.append(x[0])

            res.append(cur_line)
```

**Comment by ShangwenWang** [comment]
Hi @FalconLK 
Sorry for being late. I just finished my DDL.

I know that someone successfully reproduced my work so I really don't know the reason. My suggestion would be that since you already got the materials in the last step, you could try to train a fasttext model by slightly modifying the code.
